---
- name: install | Check current Digital Rebar version
  shell: "{{ digital_rebar_binary }} --version 2>&1 | grep {{digital_rebar_version}}"
  register: _digital_rebar_version_check
  ignore_errors: True

- name: install | Downloading Digital Rebar
  get_url:
    url: "{{ digital_rebar_dl }}"
    dest: "/tmp/{{ digital_rebar_package }}"
    checksum: "sha256:{{ digital_rebar_sha256 }}"
  when: _digital_rebar_version_check is failed

- name: install | Extracting Digital Rebar
  unarchive:
    src: "/tmp/{{ digital_rebar_package }}"
    dest: /tmp
    remote_src: true
  register: _digital_rebar_extracted
  when: _digital_rebar_version_check is failed

- name: install | Copying Digital Rebar Packages
  copy:
    src: "/tmp/bin/linux/amd64/{{ item }}"
    dest: "{{ digital_rebar_install_dir }}/{{ item }}"
    mode: "u=rwx,g=rx,o=rx"
    remote_src: true
  become: true
  with_items:
    - drpcli
    - dr-provision
    - incrementer
  when: >
        _digital_rebar_version_check is failed and
        _digital_rebar_extracted['changed']

- name: install | Creating /var/lib/dr-provision
  file:
    path: /var/lib/dr-provision
    state: directory
  become: true
